---
title: Graphing the weather
hero_image: images/banner.png
description: Learn how to plot graphical weather data from the Raspberry Pi Weather Station database
original_url: https://raspberrypi.org/learning/graphing-the-weather
theme: red
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 3, design-0, programming-3, phys-comp-0, manufacture-0, community-0
interests: weather
technologies: python
site_areas: projects
hardware: ''
software: python
version: 3
last_tested: 2017-01-01
steps: 
- title: Introduction
- title: What you will need
- title: Graphing the weather
- title: Choosing a Weather Station
- title: Getting ready
- title: Fetching your first data set
- title: Looking at JSON
- title: Getting the time and temperature
- title: Graphing the data
- title: Getting more data
- title: Finding more pages
- title: Fetching all the pages
- title: Limiting the data downloaded
- title: Finishing off with a graph
- title: What next?